# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main
trigger: none
pr: none

pool:
  default

variables:
- name: Location
  value: 'eastus'
- name: ResourceGroup
  value: 'SivaG-RG'
- name: ImageTemplateName
  value: 'imageWin11MultiTemplate'

steps:
# - task: AzureCLI@2
#   displayName: "Copy Install Script"
#   inputs:
#     azureSubscription: 'avd-pipe'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az storage blob upload \
#         --account-name sivastorageavd001 \
#         --container-name script-directory \
#         --overwrite true \
#         --name install-software.ps1 \
        # --file install-software.ps1
      
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Deploy Template"
  continueOnError: true
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'avd-pipe'
    subscriptionId: 'efb73a22-05b0-4760-bd52-733b0d730237'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroup)'
    location: '$(Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'Win11MultiTemplate.json'
    csmParametersFile: 'Win11MultiTemplate.parameters.json'
    deploymentMode: 'Incremental'

- task: AzurePowerShell@5
  displayName: "Install Az.ImageBuilder"
  inputs:
    azureSubscription: 'avd-pipe'
    ScriptType: 'InlineScript'
    Inline: 'Install-Module -name Az.ImageBuilder -AllowPrerelease -Force -Scope CurrentUser'
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: "Build Image"
  inputs:
    azureSubscription: 'avd-pipe'
    ScriptType: 'InlineScript'
    Inline: 'Start-AzImageBuilderTemplate -ResourceGroupName $(ResourceGroup) -Name $(ImageTemplateName)'
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: "Remove Template"
  inputs:
    azureSubscription: 'avd-pipe'
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzImageBuilderTemplate -ImageTemplateName $(ImageTemplateName) -ResourceGroupName $(ResourceGroup)'
    azurePowerShellVersion: 'LatestVersion'